version: '3'

services:
  app1:
    build: .
    container_name: express-app1-container
    restart: always
    environment:
      - APP_PORT=3000

  app2:
    build: .
    container_name: express-app2-container
    restart: always
    ports:
      - 3001:3000
    environment:
      - APP_PORT=3000

  app3:
    build: .
    container_name: express-app3-container
    restart: always
    ports:
      - 3002:3000
    environment:
      - APP_PORT=3000

  app4:
    build: .
    container_name: express-app4-container
    restart: always
    ports:
      - 3003:3000
    environment:
      - APP_PORT=3000

  app5:
    build: .
    container_name: express-app5-container
    restart: always
    ports:
      - 3004:3000
    environment:
      - APP_PORT=3000

  nginx:
    image: nginx:stable-alpine
    container_name: ReverseProxy-Loadbalancer-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
