apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "express-api.fullname" .}}
  labels: {{- include "express-api.labels" . | nindent 4}}
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - lucdoe.de
    secretName: {{include "express-api.fullname" .}}-tls
  rules:
    - host: lucdoe.de
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{include "express-api.fullname" .}}
                port:
                  number: 3000
