apiVersion: v1
kind: Service
metadata:
  name: {{include "express-api.fullname" .}}
  labels: {{- include "express-api.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector: {{- include "express-api.selectorLabels" . | nindent 4}}
