apiVersion: v2
name: express-api
description: A Helm chart for an Express.js API
version: 0.1.1

dependencies:
  - name: mongodb
    version: 13.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.9.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: cert-manager
    version: 1.11.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: 4.6.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
