apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "express-api.fullname" .}}
  labels: {{- include "express-api.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{- include "express-api.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "express-api.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{include "express-api.fullname" .}}
      imagePullSecrets:
        - name: my-secret
      containers:
        - name: {{.Chart.Name}}
          securityContext:
            runAsUser: 100
            runAsGroup: 101
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
